export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>

        <header>
          <p>Hey this is Header</p>
        </header>
        {children}
        <footer>testing footer</footer>
      </body>

    </html>
  )
}
